/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication3.GUI.panels;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication3.models.Location;
import javaapplication3.utils.DatabaseConnection;
import javaapplication3.utils.ObjectManager;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author aiham
 */
public class LocationPanel extends javax.swing.JPanel {
    
    DefaultTableModel tableModel;
    private static InfDB db = DatabaseConnection.getInstance();

    /**
     * Creates new form OmradePanel
     */
    public LocationPanel() {
        initComponents();
        tableModel = (DefaultTableModel) jTable2.getModel();
        loadTable();
        addListener();

    }

    private void addListener() {
        jTable2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { // Double-click
                    int row = jTable2.getSelectedRow();
                    if (row >= 0) {
                        // Assuming the first column holds the unique ID
                        int locationID = Integer.parseInt((String) jTable2.getValueAt(row, 0));
                        
                        // Fetch the Location object based on the ID
                        Location location = getLocationByID(locationID);
                        
                        // Show the dialog with location info
                        displayLocationInfo(location);
                    }
                }
            }
        }); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(200, 200, 200));
        setPreferredSize(new java.awt.Dimension(1128, 792));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Område");

        jTable2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(40, 40, 40));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Namn på plats", "Finns i"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAlignmentX(1.5F);
        jTable2.setAlignmentY(1.5F);
        jTable2.setName(""); // NOI18N
        jTable2.setRowHeight(80);
        jTable2.setRowMargin(1);
        jTable2.setRowSelectionAllowed(false);
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        jTextField1.setText("Sök här!");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Ändra information");

        jButton4.setLabel("Ta bort område");

        jButton5.setText("Lägg till område");
        jButton5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(512, 512, 512))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private Location getLocationByID(int id) {
    // Your logic to retrieve the Location object based on the id
    // This might involve searching through ObjectManager.Locations.locationList
    for (Location loc : ObjectManager.Locations.locationList) {
        if (loc.getLocationID() == id) {
            return loc;
        }
    }
    return null;
}

    private void loadTable() {
        try {
            // TODO add your handling code here:
            ObjectManager.Locations.loadList();
        } catch (NumberFormatException ex) {
            Logger.getLogger(LocationPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InfException ex) {
            Logger.getLogger(LocationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tableModel.setRowCount(0); // Clear existing rows
        
        for (Location item : ObjectManager.Locations.locationList) {
            String[] row = {Integer.toString(item.getLocationID()), item.getName(), Integer.toString(item.getExistsIn())};
            tableModel.addRow(row);
        }
    }

    
    public static void displayLocationInfo(Location location) {
    // Panel with GridLayout
    JPanel panel = new JPanel(new GridLayout(0, 2));

    // Font for the title labels
    Font boldFont = new Font("Dialog", Font.BOLD, 12);

    // Add ID title and value labels
    JLabel idTitleLabel = new JLabel("ID:");
    idTitleLabel.setFont(boldFont);
    panel.add(idTitleLabel);
    panel.add(new JLabel(Integer.toString(location.getLocationID())));

    // Add Name title and value labels
    JLabel nameTitleLabel = new JLabel("Name:");
    nameTitleLabel.setFont(boldFont);
    panel.add(nameTitleLabel);
    panel.add(new JLabel(location.getName()));

    // Add Exists in title and value labels
    JLabel existsInTitleLabel = new JLabel("Finns i:");
    existsInTitleLabel.setFont(boldFont);
    panel.add(existsInTitleLabel);
    JLabel existsInValueLabel = new JLabel();
    try {
        String existsInValue = db.fetchSingle("SELECT Benamning FROM omrade WHERE Omrades_ID = " + location.getExistsIn());
        existsInValueLabel.setText(existsInValue);
    } catch (InfException e) {
        existsInValueLabel.setText("Error fetching data");
        e.printStackTrace();
    }
    panel.add(existsInValueLabel);

    // Display the dialog
    JOptionPane.showMessageDialog(null, panel, "Location Information", JOptionPane.INFORMATION_MESSAGE);
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
