/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication3.GUI.panels;

import javaapplication3.utils.UserSession;
import oru.inf.InfDB;
import java.util.HashMap;
/**
 *
 * @Albin
 */
public class ProfilePanel extends javax.swing.JPanel {
    

    /**
     * Creates new form AgentPanel
     */
    public ProfilePanel() {
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namnPanel = new javax.swing.JPanel();
        namnText = new javax.swing.JLabel();
        namnData = new javax.swing.JLabel();
        telefonPanel = new javax.swing.JPanel();
        telefonText = new javax.swing.JLabel();
        telefonData = new javax.swing.JLabel();
        epostPanel = new javax.swing.JPanel();
        epostText = new javax.swing.JLabel();
        epostData = new javax.swing.JLabel();
        administratorPanel = new javax.swing.JPanel();
        administratorText = new javax.swing.JLabel();
        administratorData = new javax.swing.JLabel();
        tillhorOmradePanel = new javax.swing.JPanel();
        tillhorOmradeText = new javax.swing.JLabel();
        tillhorOmradeData = new javax.swing.JLabel();
        anstallningsdatumPanel = new javax.swing.JPanel();
        anstallningsdatumText = new javax.swing.JLabel();
        anstallningsDatumData = new javax.swing.JLabel();
        losenordPanel = new javax.swing.JPanel();
        losenordText = new javax.swing.JLabel();
        losenordData = new javax.swing.JLabel();
        NyttLösenButton1 = new javax.swing.JButton();
        profilTitel = new javax.swing.JLabel();
        profilBild = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 200, 200));
        setMaximumSize(new java.awt.Dimension(1128, 792));
        setMinimumSize(new java.awt.Dimension(1128, 792));
        setPreferredSize(new java.awt.Dimension(1128, 792));

        namnPanel.setPreferredSize(new java.awt.Dimension(557, 40));

        namnText.setText("NAMN:");

        namnData.setText("Fornamn Efternamn");

        javax.swing.GroupLayout namnPanelLayout = new javax.swing.GroupLayout(namnPanel);
        namnPanel.setLayout(namnPanelLayout);
        namnPanelLayout.setHorizontalGroup(
            namnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namnText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(namnData, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        namnPanelLayout.setVerticalGroup(
            namnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(namnText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(namnData))
        );

        telefonPanel.setPreferredSize(new java.awt.Dimension(557, 40));

        telefonText.setText("TELEFON:");

        telefonData.setText("07000000000");

        javax.swing.GroupLayout telefonPanelLayout = new javax.swing.GroupLayout(telefonPanel);
        telefonPanel.setLayout(telefonPanelLayout);
        telefonPanelLayout.setHorizontalGroup(
            telefonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telefonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telefonText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(telefonData, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telefonPanelLayout.setVerticalGroup(
            telefonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telefonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telefonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonData, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(telefonText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        epostText.setText("EPOST:");

        epostData.setText("mail@exempel.com");

        javax.swing.GroupLayout epostPanelLayout = new javax.swing.GroupLayout(epostPanel);
        epostPanel.setLayout(epostPanelLayout);
        epostPanelLayout.setHorizontalGroup(
            epostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epostPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(epostText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(epostData, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        epostPanelLayout.setVerticalGroup(
            epostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, epostPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(epostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(epostData))
                .addContainerGap())
        );

        administratorText.setText("ADMINISTRATÖR:");

        administratorData.setText("JA");

        javax.swing.GroupLayout administratorPanelLayout = new javax.swing.GroupLayout(administratorPanel);
        administratorPanel.setLayout(administratorPanelLayout);
        administratorPanelLayout.setHorizontalGroup(
            administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(administratorText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(administratorData, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        administratorPanelLayout.setVerticalGroup(
            administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(administratorText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(administratorData))
                .addContainerGap())
        );

        tillhorOmradeText.setText("TILLHÖR OMRÅDE:");

        tillhorOmradeData.setText("Norr");

        javax.swing.GroupLayout tillhorOmradePanelLayout = new javax.swing.GroupLayout(tillhorOmradePanel);
        tillhorOmradePanel.setLayout(tillhorOmradePanelLayout);
        tillhorOmradePanelLayout.setHorizontalGroup(
            tillhorOmradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tillhorOmradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tillhorOmradeText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tillhorOmradeData, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tillhorOmradePanelLayout.setVerticalGroup(
            tillhorOmradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tillhorOmradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tillhorOmradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tillhorOmradeText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tillhorOmradeData))
                .addContainerGap())
        );

        anstallningsdatumText.setText("ANSTÄLLNINGSDATUM:");

        anstallningsDatumData.setText("2023-10-24");

        javax.swing.GroupLayout anstallningsdatumPanelLayout = new javax.swing.GroupLayout(anstallningsdatumPanel);
        anstallningsdatumPanel.setLayout(anstallningsdatumPanelLayout);
        anstallningsdatumPanelLayout.setHorizontalGroup(
            anstallningsdatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anstallningsdatumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anstallningsdatumText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anstallningsDatumData, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        anstallningsdatumPanelLayout.setVerticalGroup(
            anstallningsdatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anstallningsdatumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(anstallningsdatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anstallningsdatumText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(anstallningsDatumData))
                .addContainerGap())
        );

        losenordText.setText("LÖSENORD:");

        losenordData.setText("*****");

        javax.swing.GroupLayout losenordPanelLayout = new javax.swing.GroupLayout(losenordPanel);
        losenordPanel.setLayout(losenordPanelLayout);
        losenordPanelLayout.setHorizontalGroup(
            losenordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losenordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(losenordText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(losenordData, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        losenordPanelLayout.setVerticalGroup(
            losenordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losenordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(losenordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenordText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(losenordData))
                .addContainerGap())
        );

        NyttLösenButton1.setText("NYTT LÖSENORD");
        NyttLösenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyttLösenButton1ActionPerformed(evt);
            }
        });

        profilTitel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        profilTitel.setText("DIN PROFIL");

        profilBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AgentBild.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(NyttLösenButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(losenordPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tillhorOmradePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(administratorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anstallningsdatumPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(epostPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namnPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profilTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(profilBild)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profilTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(namnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(epostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(telefonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anstallningsdatumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(administratorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tillhorOmradePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(losenordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NyttLösenButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(profilBild)
                .addContainerGap(473, Short.MAX_VALUE))
        );

        namnPanel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void NyttLösenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyttLösenButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NyttLösenButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NyttLösenButton1;
    private javax.swing.JLabel administratorData;
    private javax.swing.JPanel administratorPanel;
    private javax.swing.JLabel administratorText;
    private javax.swing.JLabel anstallningsDatumData;
    private javax.swing.JPanel anstallningsdatumPanel;
    private javax.swing.JLabel anstallningsdatumText;
    private javax.swing.JLabel epostData;
    private javax.swing.JPanel epostPanel;
    private javax.swing.JLabel epostText;
    private javax.swing.JLabel losenordData;
    private javax.swing.JPanel losenordPanel;
    private javax.swing.JLabel losenordText;
    private javax.swing.JLabel namnData;
    private javax.swing.JPanel namnPanel;
    private javax.swing.JLabel namnText;
    private javax.swing.JLabel profilBild;
    private javax.swing.JLabel profilTitel;
    private javax.swing.JLabel telefonData;
    private javax.swing.JPanel telefonPanel;
    private javax.swing.JLabel telefonText;
    private javax.swing.JLabel tillhorOmradeData;
    private javax.swing.JPanel tillhorOmradePanel;
    private javax.swing.JLabel tillhorOmradeText;
    // End of variables declaration//GEN-END:variables
}
