/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaapplication3.GUI;
import java.awt.Color;

/**
 *
 * @author aiham
 */
public class RegisterNewAreaDialog extends javax.swing.JDialog {

    /**
     * Creates new form addAreaDialog, blir problem med färgerna på popuppen. 
     */
    public RegisterNewAreaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(51,51,51));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameOfArea = new javax.swing.JLabel();
        addAreaText = new javax.swing.JLabel();
        valueOfId = new javax.swing.JLabel();
        confirmAddArea = new javax.swing.JButton();
        abortAddArea1 = new javax.swing.JButton();
        nameOfNewArea = new javax.swing.JTextField();
        areaID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(60, 63, 65));
        setName("addArea"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 650));

        nameOfArea.setBackground(new java.awt.Color(221, 221, 221));
        nameOfArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameOfArea.setText("Benämning på Område:");

        addAreaText.setBackground(new java.awt.Color(221, 221, 221));
        addAreaText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addAreaText.setText("Lägg till Område");

        valueOfId.setBackground(new java.awt.Color(221, 221, 221));
        valueOfId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valueOfId.setText("ID:");

        confirmAddArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmAddArea.setText("Bekräfta");
        confirmAddArea.setToolTipText("");
        confirmAddArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddAreaActionPerformed(evt);
            }
        });

        abortAddArea1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        abortAddArea1.setText("Avbryt");
        abortAddArea1.setToolTipText("");
        abortAddArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortAddArea1ActionPerformed(evt);
            }
        });

        areaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(abortAddArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(confirmAddArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(valueOfId)
                            .addGap(55, 55, 55)
                            .addComponent(nameOfArea)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addAreaText)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areaID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(nameOfNewArea, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(addAreaText)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valueOfId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameOfArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameOfNewArea, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abortAddArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmAddArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddAreaActionPerformed

    }//GEN-LAST:event_confirmAddAreaActionPerformed

    private void abortAddArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortAddArea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abortAddArea1ActionPerformed

    private void areaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortAddArea1;
    private javax.swing.JLabel addAreaText;
    private javax.swing.JTextField areaID;
    private javax.swing.JButton confirmAddArea;
    private javax.swing.JLabel nameOfArea;
    private javax.swing.JTextField nameOfNewArea;
    private javax.swing.JLabel valueOfId;
    // End of variables declaration//GEN-END:variables
}
